### PR TITLE
Use HWC Buildpack instead of binary buildpack

### PR DESCRIPTION
**Pull request by HDYA**
Otherwise the app won't start.

2017-08-23T15:47:52.42+0800 [APP/PROC/WEB/0] ERR Warning: We detected a Web.config in your app. This probably means t
hat you want to use the hwc-buildpack. If you really want to use the binary-buildpack, you must specify a start command.

### CODE REVIEW

**Comment by crawsible** [comment]
@HDYA Hey there, thanks for the fix! Have you signed the CLA, or work for a company that has signed the CLA?

**Comment by HDYA** [comment]
@crawsible Hi~ I work for Microsoft ARD, sorry I haven't join the organization.

**Comment by crawsible** [comment]
@HDYA Is there any chance you can publicize your membership to Microsoft ARD with a Github org?

**Comment by crawsible** [comment]
@HDYA Never mind, I see you've made your Azure org membership public. Going to close and reopen this issue to retrigger the bot.

**Comment by crawsible** [comment]
Looks good @HDYA, thanks for the fix!

**Comment by HDYA** [comment]
Thanks a lot @crawsible ! Awesome automation solution.

**Pull request merged**
